#!/bin/bash
sudo apt-get install python-pip
sudo apt install python-elasticsearch
sudo apt-get install xdot
sudo apt install nmap
sudo apt install openjdk-8-jdk
sudo apt install msfconsole
sudo apt install python3-libnmap
sudo apt install python3-dateutil

sudo npm install shodan -g
sudo apt-add-repository ppa:ansible/ansible
sudo apt update -y
sudo apt install ansible -y

sudo apt install python-xmltodict
sudo apt install npm

sudo npm install shodan -g
sudo apt install metasploit-framework
sudo apt install ansible
npm install npm
npm install
npm audit fix

pip install -r requirements.txt
sudo apt install sshpass

mkdir ./reports
mkdir ./data
mkdir web/graphs
mkdir ./lists
mkdir ./web/graphs
