---
- hosts: all
  vars_prompt:

    - name: username
      prompt: "What is your username?"
      private: no

    - name: password
      prompt: "What is your password?"

    - name: privatekey
      prompt: "What is your Private Key?"

  tasks:
    - debug:
        msg: 'Logging in as {{ username }}'

    - shell:
        cmd : "ls"
        cmd: 'scripts/ssh_setup.sh {{ privatekey }}'
        
    - wincommand:
        #add windows
        stdin: 'dir'
        