---
- hosts: all
  vars_prompt:

    - name: username
      prompt: "What is your username?"
      private: no

    - name: password
      prompt: "What is your password?"

    - name: publickey
      prompt: "What is your Public Key?"

  tasks:

    - shell: 'echo "{{ publickey }}" >> ~/.ssh/authorized_keys'
    - shell: 'cat ~/.ssh/authorized_keys'
      register: fileout
    
    - debug: msg="Logging in as {{username}} {{ fileout.stdout_lines }} "
    


