---
- hosts: all
  vars_prompt:

    - name: username
      prompt: "What is your username?"
      private: no

    - name: password
      prompt: "What is your password?"

    - name: privatekey
      prompt: "What is your Private Key?"

  tasks:
    - debug:
        msg: 'Logging in as {{ username }}'

    - shell:
        cmd : "ls"
        cmd: 'scripts/ssh_setup.sh {{ privatekey }}'
        
    - name: Run the setup.exe installer on multiple servers using the Domain Administrator
      win_psexec:
        command: E:\setup.exe /i /IACCEPTEULA
        hostnames:
        - remote_server1
        - remote_server2
        username: DOMAIN\username
        password: some_password
        priority: high